# Generated by Django 4.2.2 on 2023-06-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('Student', 'Student'), ('Collaborator', 'Collaborator')], default='Student', max_length=20),
        ),
    ]
