# Generated by Django 4.2.2 on 2023-06-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_type_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff')], default='Student', max_length=20),
        ),
    ]
