# Generated by Django 4.2.2 on 2023-07-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unblocked_date',
            field=models.DateField(null=True),
        ),
    ]
