# Generated by Django 4.2.2 on 2023-06-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='user',
            new_name='followers',
        ),
    ]
