# Generated by Django 4.2.2 on 2023-06-29 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_rename_user_books_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='followers',
        ),
        migrations.AddField(
            model_name='books',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='Books', to=settings.AUTH_USER_MODEL),
        ),
    ]
