# Generated by Django 4.2.2 on 2023-06-30 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_remove_books_followers_books_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='followers',
            field=models.ManyToManyField(related_name='Books', to=settings.AUTH_USER_MODEL),
        ),
    ]
