# Generated by Django 4.2.2 on 2023-07-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lend_date", models.DateField(auto_now_add=True)),
                ("return_date", models.DateField(null=True)),
                ("returned_date", models.DateField(null=True)),
                ("traffic_ticket", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lent", "Lent"),
                            ("overdue", "Overdue"),
                            ("returned", "Returned"),
                        ],
                        default="lent",
                        max_length=10,
                    ),
                ),
                (
                    "copy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="copies.copy",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
