# Generated by Django 4.2.2 on 2023-07-07 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lendings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lending",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lendings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
