# Generated by Django 4.2.2 on 2023-07-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lendings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lending",
            name="traffic_ticket",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
