# Generated by Django 4.2.2 on 2023-07-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='traffic_ticket',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
